# Copyright by @hoojo
# hoojo.me@gmail.com
# create by 2018-09-13
# @changelog hyperledger fabric network generator tools settings


# -----------------------------------------------------------------
# settings: setter output location, orderer & peer Organization
# -----------------------------------------------------------------
settings:

  # Output fabric network config directory Generator Settings
  output: D:\workspace_blockchain_chaincode\blockchain-fabric-network\prod

  # OrdererType: kafka | solo
  orderer_type: kafka

  # Orderer Organization Generator Settings
  orderers:
    - name: Orderer
      domain: hoojo.orderer
      hostnames: [org1st, org2nd]

  # Peer Organization Generator Settings
  peers:
    - name: Org1
      domain: hoojo.me
      hostnames: [peer1st, peer2nd]
      user_count: 2

    - name: Org2
      domain: hoojo.top
      hostnames: [peer3rd, peer4th]
      user_count: 2

  zookeeper:
    domain: hoojo.com
    count: 3

  kafka:
    domain: hoojo.com
    count: 4