# Copyright by @hoojo
# hoojo.me@gmail.com
# create by 2018-09-13
# hyperledger fabric network generator tools settings


# -----------------------------------------------------------------
# settings: setter output location, orderer & peer Organization
# -----------------------------------------------------------------
settings:

  # Output fabric network config directory Generator Settings
  output: D:\workspace_blockchain_masget\blockchain-fabric-network\prod

  # OrdererType: kafka | solo
  orderer_type: kafka

  # Orderer Organization Generator Settings
  orderers:
    - name: Orderer
      domain: orderer.masget.com
      hostnames: [first, last]

  # Peer Organization Generator Settings
  peers:
    - name: Org1
      domain: masget.com
      hostnames: [master, worker]
      user_count: 2
      template_count: 2

    - name: Org2
      domain: masget.com
      hostnames: [master, worker]
      user_count: 2
      template_count: 2

  zookeeper:
    domain: masget.com
    count: 4

  kafka:
    domain: masget.com
    count: 4
