version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  couchdb: &couchdb-base
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC_COUCHDB}
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    expose:
      - 5984
    deploy: &couchdb-deploy-common
      #mode: global
      mode: replicated
      replicas: 4
      #resources:
        #limits:
          #cpus: "0.25"
          #memory: 3000M
      restart_policy:
        condition: on-failure


#-----------------------------------------------------------------------------------
# couchdb & peer service yaml
#-----------------------------------------------------------------------------------
services:
  couchdb0:
    container_name: couchdb0
    hostname: couchdb0.simple.com
    <<: *couchdb-base
    ports:
      - "5984:5984"
    networks:
      blockchain_net:
        aliases:
          - couchdb0.simple.com

  couchdb1:
    container_name: couchdb1
    hostname: couchdb1.simple.com
    <<: *couchdb-base
    networks:
      blockchain_net:
        aliases:
          - couchdb1.simple.com

  couchdb2:
    container_name: couchdb2
    hostname: couchdb2.simple.com
    <<: *couchdb-base
    networks:
      blockchain_net:
        aliases:
          - couchdb2.simple.com

  couchdb3:
    container_name: couchdb3
    hostname: couchdb3.simple.com
    <<: *couchdb-base
    networks:
      blockchain_net:
        aliases:
          - couchdb3.simple.com

  peer0_org1:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb0
      
  peer1_org1:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb1  
      
  peer0_org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb2  
      
  peer1_org2:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb3  
