# hyperledger fabric network generator tools
# Copyright by @hoojo
# hoojo.me@gmail.com create by 2018-09-12
# @changelog hyperledger fabric network generator tools orderer & peer template defined


{% from 'commons-macro/global-macro.yaml' import render_orderer, render_peer, render_depends, dump_orderers, dump_peers with context %}
{% from 'commons-macro/global-macro.yaml' import render_orderer_clientrootcas, render_orderer_volumes, fabric with context %}
{% from 'commons-macro/global-macro.yaml' import render_peer_orderer_depend, render_peer_depend with context %}
version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  orderer-base: &orderer-base
    image: hyperledger/fabric-orderer${IMAGE_TAG_FABRIC}
    environment: &orderer-env-common
      ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0

      ORDERER_GENERAL_GENESISMETHOD: file
      ORDERER_GENERAL_GENESISFILE: /etc/hyperledger/configtx/genesis.block
      ORDERER_GENERAL_LOCALMSPDIR: /etc/hyperledger/msp/orderer/msp
      
      # enabled TLS
      ORDERER_GENERAL_TLS_ENABLED: ${HYPERLEDGER_FABRIC_ENABLE_TLS}
      ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED: ${HYPERLEDGER_FABRIC_ENABLE_CLIENT_AUTH_REQUIRED}
      ORDERER_GENERAL_TLS_PRIVATEKEY: /etc/hyperledger/msp/orderer/tls/server.key
      ORDERER_GENERAL_TLS_CERTIFICATE: /etc/hyperledger/msp/orderer/tls/server.crt
      ORDERER_GENERAL_TLS_ROOTCAS: "[/etc/hyperledger/msp/orderer/tls/ca.crt]"
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    deploy:
      #mode: global
      mode: replicated
      replicas: 4
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 5000M
      restart_policy:
        condition: on-failure
      #placement:
      #  constraints: [node.role == manager]
    depends_on:
%{ render_depends('zookeeper', zookeeper_count) -}
%{ render_depends('kafka', kafka_count) }

  peer-base: &peer-base
    image: hyperledger/fabric-peer${IMAGE_TAG_FABRIC}
    environment: &peer-env-common
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: fabric_blockchain_net
      #CORE_LOGGING_LEVEL: ERROR
      CORE_LOGGING_LEVEL: DEBUG
      # endorser enabled
      CORE_PEER_ENDORSER_ENABLED: "true"
      CORE_PEER_GOSSIP_USELEADERELECTION: "true"
      CORE_PEER_GOSSIP_ORGLEADER: "false"
      # channel service enalbed
      CORE_PEER_CHANNELSERVICE_ENABLED: "true"
      # The following setting skips the gossip handshake since we are not doing mutual TLS
      CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/msp/peer/msp
      # skip phandshake
      CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"
      
      ########## profile enabled: true
      CORE_PEER_PROFILE_ENABLED: "false"
      CORE_PEER_TLS_ENABLED: ${HYPERLEDGER_FABRIC_ENABLE_TLS}
      CORE_PEER_TLS_CLIENTAUTHREQUIRED: ${HYPERLEDGER_FABRIC_ENABLE_CLIENT_AUTH_REQUIRED}
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/msp/peer/tls/server.crt
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/msp/peer/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/msp/peer/tls/ca.crt

      # NOTE BOTH below should never be used in production.
      CORE_PEER_AUTHENTICATION_TIMEWINDOW: 3600s
      CORE_PEER_EVENTS_TIMEWINDOW: 3600s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    deploy:
      #mode: global
      mode: replicated
      replicas: 4
      #resources:
        #limits:
          #cpus: "0.25"
          #memory: 2500M
      restart_policy:
        condition: on-failure


services:
{% call(orderer, domain, hostname) dump_orderers(true) %}
  {% set orderer_host = hostname | lower ~ '.' ~ domain | lower %}
  {% set orderer_name = hostname ~ '_' ~ orderer.name | lower if hostname != orderer.name | lower else hostname %}
  %{orderer_name }:
    container_name: %{orderer_host }
    <<: *orderer-base
    environment:
      <<: *orderer-env-common
      ORDERER_GENERAL_LOCALMSPID: %{orderer.name | title }MSP
      ORDERER_GENERAL_LOGLEVEL: debug
      ORDERER_GENERAL_TLS_CLIENTROOTCAS: "[%{render_orderer_clientrootcas() }]"
      GRPC_TRACE: all=true,
      GRPC_VERBOSITY: debug
      ORDERER_GENERAL_AUTHENTICATION_TIMEWINDOW: 3600s #Not for production -- remove.

      # new add Kafka config
      ORDERER_KAFKA_RETRY_SHORTINTERVAL: 1s
      ORDERER_KAFKA_RETRY_SHORTTOTAL: 60s
      ORDERER_KAFKA_VERBOSE: "true"
    volumes:
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/channel-artifacts:/etc/hyperledger/configtx:ro
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/ordererOrganizations/%{domain }/orderers/%{orderer_host }/:/etc/hyperledger/msp/orderer:ro
%{ render_orderer_volumes() }
    ports:
      - %{fabric.orderer_count + 7}050:7050
    {% set fabric.orderer_count = fabric.orderer_count + 1 %}
{% endcall %}


{% call(peer, domain, hostname) dump_peers(true) %}
  {% set peer_host = hostname | lower ~ '.' ~ domain | lower %}
  {% set peer_name = hostname | lower ~ '_' ~ peer.name | lower %}
  %{peer_name }:
    container_name: %{peer_host }
    <<: *peer-base
    environment:
      <<: *peer-env-common
      CORE_PEER_ID: %{peer_host }
      CORE_PEER_ADDRESS: %{peer_host }:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: %{peer_host }:7051
      #CORE_PEER_GOSSIP_ORGLEADER: true
      CORE_PEER_LOCALMSPID: %{peer.name | title }MSP

      #CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/msp/peer/msp/cacerts/ca.%{domain }-cert.pem
      CORE_PEER_TLS_CLIENTROOTCAS_FILES: /etc/hyperledger/msp/peer/msp/tlscacerts/tlsca.%{domain }-cert.pem

      # NEW ADD
      CORE_PEER_CHAINCODEADDRESS: %{peer_host }:7052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_BOOTSTRAP: %{peer_host }:7051
      #CORE_PEER_GOSSIP_BOOTSTRAP: peer1.%{domain }:7051

      # v1.2
      # CORE_PEER_LISTENADDRESS: %{peer_host }:7051
      CORE_PEER_GOSSIP_ENDPOINT: %{peer_host }:7051
      CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/%{domain }/peers/%{peer_host }/:/etc/hyperledger/msp/peer:ro
    ports:
      - %{fabric.peer_count + 7}051:7051
      - %{fabric.peer_count + 7}052:7052
      - %{fabric.peer_count + 7}053:7053
    depends_on:
%{render_peer_orderer_depend() -}
%{render_peer_depend(peer, peer_name) }
    {% set fabric.peer_count = fabric.peer_count + 1 %}
{% endcall %}