version: '3.6'

networks:
  external_monitor_net:
    external:
      name: monitor_net

services:
  # 0.1
  ca0:
    networks:
      - external_monitor_net    

  ca1:
    networks:
      - external_monitor_net
  
  # 0.15  
  zookeeper0:
    networks:
      - external_monitor_net

  zookeeper1:
    networks:
      - external_monitor_net

  zookeeper2:
    networks:
      - external_monitor_net
  
  # 0.2
  kafka0:
    networks:
      - external_monitor_net

  kafka1:
    networks:
      - external_monitor_net

  kafka2:
    networks:
      - external_monitor_net

  kafka3:
    networks:
      - external_monitor_net

  #### 0.5
  orderer:
    networks:
      - external_monitor_net

  peer0_org1:
    networks:
      - external_monitor_net

  peer1_org1:
    networks:
      - external_monitor_net

  peer0_org2:
    networks:
      - external_monitor_net

  peer1_org2:
    networks:
      - external_monitor_net
  
  configtxlator:
    networks:
      - external_monitor_net
    
  ccenv:
    networks:
      - external_monitor_net
    
  visualizer:
    networks:
      - external_monitor_net    
         