# hyperledger fabric network generator tools
# Copyright by @hoojo
# hoojo.me@gmail.com create by 2018-09-12
# @changelog hyperledger fabric network generator tools fabric monitor network template defined

{% from 'commons-macro/global-macro.yaml' import dump_orderers, dump_peers with context %}
version: '3.6'

networks:
  external_monitor_net:
    external:
      name: monitor_net

services:
#-----------------------------------------------------------------------------------
# ca service yaml
#-----------------------------------------------------------------------------------
  # 0.1
{% for peer in peers %}
  ca%{loop.index0 }:
    networks:
      - external_monitor_net    
{% endfor %}

#-----------------------------------------------------------------------------------
# zookeeper service yaml
#-----------------------------------------------------------------------------------
  # 0.15
{% for index in range(zookeeper.count) %}
  zookeeper%{ index }:
    networks:
      - external_monitor_net
{% endfor %}

#-----------------------------------------------------------------------------------
# kafka service yaml
#-----------------------------------------------------------------------------------
  # 0.2
{% for index in range(kafka.count) %}
  kafka%{ index }:
    networks:
      - external_monitor_net
{% endfor %}

%#-----------------------------------------------------------------------------------
%# orderer service yaml
%#-----------------------------------------------------------------------------------
  #### 0.5
{% call(orderer, domain, hostname) dump_orderers(true) %}
  {% set orderer_name = hostname ~ '_' ~ orderer.name | lower if hostname != orderer.name | lower else hostname %}
  %{orderer_name }:
    networks:
      - external_monitor_net
{% endcall %}

%#-----------------------------------------------------------------------------------
%# peer service yaml
%#-----------------------------------------------------------------------------------
{% call(peer, domain, hostname) dump_peers(true) %}
  {% set peer_name = hostname | lower ~ '_' ~ peer.name | lower %}
  %{peer_name }:
    networks:
      - external_monitor_net
{% endcall %}

  configtxlator:
    networks:
      - external_monitor_net
    
  ccenv:
    networks:
      - external_monitor_net
    
  visualizer:
    networks:
      - external_monitor_net    
         