version: '3.6'

#-----------------------------------------------------------------------------------
# visualizer service yaml
#-----------------------------------------------------------------------------------
services:
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"    
    networks:
      - blockchain_net      
    ports:
      - "3100:8080"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:  
        limits:
          cpus: '0.15'
          #memory: 1000M
        reservations:
          cpus: '0.1'
          #memory: 500M          