# hyperledger fabric network generator tools
# Copyright by @hoojo
# hoojo.me@gmail.com create by 2018-09-12
# @changelog hyperledger fabric network generator tools fabric template defined

{% from 'commons-macro/global-macro.yaml' import dump_peers with context %}
version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  couchdb: &couchdb-base
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC_COUCHDB}
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    expose:
      - 5984
    deploy: &couchdb-deploy-common
      #mode: global
      mode: replicated
      replicas: 4
      #resources:
        #limits:
          #cpus: "0.25"
          #memory: 3000M
      restart_policy:
        condition: on-failure


#-----------------------------------------------------------------------------------
# couchdb & peer service yaml
#-----------------------------------------------------------------------------------
services:
{% set ns = namespace(first_peer=true) %}

{% call(peer, domain, hostname, loop) dump_peers() %}
  {% set peer_host = hostname | lower ~ '.' ~ domain | lower %}
  {% set peer_name = hostname | lower ~ '_' ~ peer.name | lower %}
  couchdb_%{peer_name | lower }:
    container_name: couchdb.%{peer_host }
        hostname: couchdb.%{peer_host }
        <<: *couchdb-base
    {% if ns.first_peer %}
        {% set ns.first_peer = false %}
        ports:
          - "5984:5984"
    {% endif %}
        networks:
          blockchain_net:
            aliases:
              - couchdb.%{peer_host }
{% endcall %}

{% call(peer, domain, hostname) dump_peers(true) %}
  {% set peer_host = hostname | lower ~ '.' ~ domain | lower %}
  {% set peer_name = hostname | lower ~ '_' ~ peer.name | lower %}
  %{peer_name }:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_%{peer_name | lower }:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdb_%{peer_name | lower }
{% endcall %}