version: '3.6'

#-----------------------------------------------------------------------------------
# base service yaml
#-----------------------------------------------------------------------------------
x-base-services:
  ca: &ca-base
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment: &ca-env-common
      FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
      FABRIC_CA_SERVER_TLS_ENABLED: ${HYPERLEDGER_FABRIC_ENABLE_TLS}
    deploy: &ca-deploy-common
      #mode: global
      mode: replicated
      replicas: 4
      #resources:
        #limits:
          #cpus: "0.2"
          #memory: 2000M
      restart_policy:
        condition: on-failure   


#-----------------------------------------------------------------------------------
# networks yaml
#-----------------------------------------------------------------------------------
networks:
  blockchain_net:
    driver: overlay
    attachable: true


#-----------------------------------------------------------------------------------
# core service yaml
#-----------------------------------------------------------------------------------
services:
  ca0:
    container_name: ca.foo.com
    hostname: ca.foo.com
    <<: *ca-base
    environment:
      <<: *ca-env-common
      FABRIC_CA_SERVER_CA_NAME: ca-org1
      FABRIC_CA_SERVER_TLS_KEYFILE: /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY  
      FABRIC_CA_SERVER_TLS_CERTFILE: /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem
    command: sh -c "fabric-ca-server start ${V11_IDENTITIES_ALLOWREMOVE} ${V11_AFFILIATIONS_ALLOWREMOVE} --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d"
    #command: sh -c "fabric-ca-server start -n ca-org1 ${V11_IDENTITIES_ALLOWREMOVE} ${V11_AFFILIATIONS_ALLOWREMOVE} --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw ${HYPERLEDGER_FABRIC_ENABLE_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.foo.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -d"
    ports:
      - "7054:7054"
    volumes:
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org1.foo.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    networks:
      blockchain_net:
        aliases:
          - ca.foo.com           

  ca1:
    container_name: ca.bar.com
    hostname: ca.bar.com
    <<: *ca-base
    environment:
      <<: *ca-env-common
      FABRIC_CA_SERVER_CA_NAME: ca-org2
      FABRIC_CA_SERVER_TLS_KEYFILE: /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
      FABRIC_CA_SERVER_TLS_CERTFILE: /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem
    command: sh -c "fabric-ca-server start --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d"
    #command: sh -c "fabric-ca-server start --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw ${HYPERLEDGER_FABRIC_ENABLE_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.bar.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -d"
    ports:
      - "8054:7054"
    volumes:
      - ./fabric-configs/${FABRIC_NETWORK_CONFIGTX_VERSION}/crypto-config/peerOrganizations/org2.bar.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    networks:
      blockchain_net:
        aliases:
          - ca.bar.com        

#-----------------------------------------------------------------------------------
# tools service yaml
#-----------------------------------------------------------------------------------  
  configtxlator:
    container_name: configtxlator.com
    hostname: configtxlator.com
    image: hyperledger/fabric-tools${IMAGE_TAG_FABRIC}    
    command: /usr/local/bin/configtxlator start
    ports:
      - "7059:7059"
    networks:
      blockchain_net:
        aliases:
          - configtxlator.com
    deploy:
      replicas: 2
      #resources:
        #limits:
          #cpus: "0.1"
          #memory: 500M
      restart_policy:
        condition: on-failure  

  ccenv:
    container_name: ccenv
    image: hyperledger/fabric-ccenv${IMAGE_TAG_FABRIC}
    networks:
      - blockchain_net
    deploy:
      replicas: 2
      #resources:
        #limits:
          #cpus: "0.1"
          #memory: 2000M
      restart_policy:
        condition: on-failure


#-----------------------------------------------------------------------------------
# zookeeper service yaml
#-----------------------------------------------------------------------------------
  zookeeper0:
    hostname: zookeeper0.simple.com
    networks:
      blockchain_net:
        aliases:
          - zookeeper0.simple.com

  zookeeper1:
    hostname: zookeeper1.simple.com
    networks:
      blockchain_net:
        aliases:
          - zookeeper1.simple.com

  zookeeper2:
    hostname: zookeeper2.simple.com
    networks:
      blockchain_net:
        aliases:
          - zookeeper2.simple.com


#-----------------------------------------------------------------------------------
# kafka service yaml
#-----------------------------------------------------------------------------------
  kafka0:
    hostname: kafka0.simple.com
    networks:
      blockchain_net:
        aliases:
          - kafka0.simple.com

  kafka1:
    hostname: kafka1.simple.com
    networks:
      blockchain_net:
        aliases:
          - kafka1.simple.com
 
  kafka2:
    hostname: kafka2.simple.com
    networks:
      blockchain_net:
        aliases:
          - kafka2.simple.com

  kafka3:
    hostname: kafka3.simple.com
    networks:
      blockchain_net:
        aliases:
          - kafka3.simple.com


#-----------------------------------------------------------------------------------
# orderer & peer service yaml
#-----------------------------------------------------------------------------------
  orderer:
    hostname: orderer.simple.com
    networks:
      blockchain_net:
        aliases:
          - orderer.simple.com

  peer0_org1:
    hostname: peer0.org1.foo.com 
    networks:
      blockchain_net:
        aliases:
          - peer0.org1.foo.com

  peer1_org1:
    hostname: peer1.org1.foo.com 
    networks:
      blockchain_net:
        aliases:
          - peer1.org1.foo.com  

  peer0_org2:
    hostname: peer0.org2.bar.com 
    networks:
      blockchain_net:
        aliases:
          - peer0.org2.bar.com  

  peer1_org2:
    hostname: peer1.org2.bar.com 
    networks:
      blockchain_net:
        aliases:
          - peer1.org2.bar.com